In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    'I love programming in Python',
    'Python is a great programming language',
    'I enjoy solving problems with Python',
    'Python is versatile and powerful',
    'I love learning new things in Python',
    'Python is my favorite programming language',
    'I enjoy coding in Python'
]

In [3]:
## define the vocabulary size
voc_size = 10000

In [4]:
## One hot representation for every word
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2402, 9418, 5307, 3653, 1645],
 [1645, 3656, 9351, 9384, 5307, 4124],
 [2402, 9980, 5240, 4811, 8771, 1645],
 [1645, 3656, 8351, 1392, 823],
 [2402, 9418, 2537, 5207, 4278, 3653, 1645],
 [1645, 3656, 5565, 3622, 5307, 4124],
 [2402, 9980, 3618, 3653, 1645]]

In [5]:
## word embedding representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [9]:
sent_lenght = 8
embedded_docs = pad_sequences(one_hot_repr, maxlen=sent_lenght, padding='pre')
embedded_docs


array([[   0,    0,    0, 2402, 9418, 5307, 3653, 1645],
       [   0,    0, 1645, 3656, 9351, 9384, 5307, 4124],
       [   0,    0, 2402, 9980, 5240, 4811, 8771, 1645],
       [   0,    0,    0, 1645, 3656, 8351, 1392,  823],
       [   0, 2402, 9418, 2537, 5207, 4278, 3653, 1645],
       [   0,    0, 1645, 3656, 5565, 3622, 5307, 4124],
       [   0,    0,    0, 2402, 9980, 3618, 3653, 1645]])

In [10]:
embedded_docs.shape

(7, 8)

In [11]:
## feature representation
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_lenght))
model.compile('adam', 'mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 93ms/step


array([[[-0.0476831 , -0.02807511, -0.03648119,  0.04835023,
          0.04755307,  0.01046009,  0.04244944, -0.04786822,
          0.04743314,  0.03818041],
        [-0.0476831 , -0.02807511, -0.03648119,  0.04835023,
          0.04755307,  0.01046009,  0.04244944, -0.04786822,
          0.04743314,  0.03818041],
        [-0.0476831 , -0.02807511, -0.03648119,  0.04835023,
          0.04755307,  0.01046009,  0.04244944, -0.04786822,
          0.04743314,  0.03818041],
        [ 0.04956771,  0.04550213, -0.01468379, -0.04987202,
          0.00671323, -0.047213  , -0.00207973, -0.03796244,
         -0.01954134, -0.02693008],
        [ 0.01783622, -0.01647954,  0.04437807,  0.03044267,
          0.0363161 , -0.01553426,  0.03585205,  0.04664588,
          0.02451092, -0.04486496],
        [ 0.01914435,  0.00694843,  0.03007717,  0.04566662,
          0.02428157,  0.00437279,  0.02710016,  0.01667035,
         -0.01272283,  0.02812756],
        [-0.01202927,  0.02266974,  0.00323026,  0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0, 2402, 9418, 5307, 3653, 1645])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 45ms/step


array([[-0.0476831 , -0.02807511, -0.03648119,  0.04835023,  0.04755307,
         0.01046009,  0.04244944, -0.04786822,  0.04743314,  0.03818041],
       [-0.0476831 , -0.02807511, -0.03648119,  0.04835023,  0.04755307,
         0.01046009,  0.04244944, -0.04786822,  0.04743314,  0.03818041],
       [-0.0476831 , -0.02807511, -0.03648119,  0.04835023,  0.04755307,
         0.01046009,  0.04244944, -0.04786822,  0.04743314,  0.03818041],
       [ 0.04956771,  0.04550213, -0.01468379, -0.04987202,  0.00671323,
        -0.047213  , -0.00207973, -0.03796244, -0.01954134, -0.02693008],
       [ 0.01783622, -0.01647954,  0.04437807,  0.03044267,  0.0363161 ,
        -0.01553426,  0.03585205,  0.04664588,  0.02451092, -0.04486496],
       [ 0.01914435,  0.00694843,  0.03007717,  0.04566662,  0.02428157,
         0.00437279,  0.02710016,  0.01667035, -0.01272283,  0.02812756],
       [-0.01202927,  0.02266974,  0.00323026,  0.01939179,  0.02493575,
         0.00576349, -0.00121453, -0.04803863